server:
  port: 8080
  servlet:
    session:
      persistent: false
spring:
  application:
    name: ROOT
zuul:
  routes:
    users:
      url: http://localhost:8081/users
    blogs:
      url: http://localhost:8082/blogs
ribbon:
  eureka:
    enabled: false


