server:
  port: 8081
spring:
  application:
#    name: user
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: dev
  cache:
    redis:
      cacheNullValues: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  session:
    store-type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java-web?serverTimezone=GMT%2B8
    username: root
    password: 123456
logging:
  level:
    web: info
    org:
      springframework:
        security: debug
      mybatis: warn
mybatis:
  type-aliases-package: space.nature.web.user.domain
  mapper-locations: classpath:mapper/*.xml

