server:
  port: 8081
  servlet:
    context-path: /users
    session:
      persistent: false
spring:
  application:
    name: user
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: dev
  cache:
    redis:
      cacheNullValues: false
  redis:
    database: 1
    jedis:
      pool:
        max-idle: 3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/worlds?serverTimezone=GMT%2B8
    username: root
    password: 123456
  security:
    loginPageUrl: http://localhost/login.html
    jwt:
      timeout: 10
logging:
  level:
    web: info
    org:
      springframework:
        security: info
      mybatis: warn
mybatis:
  type-aliases-package: space.nature.web.user.domain
  mapper-locations: classpath:mapper/*.xml

